### ISSUE TITLE
No way to zero or pull gyros data from python implementation of pigeon2

### ISSUE THREAD

**Issue by Lagor845** [CrossTheRoadElec/Phoenix6-Documentation#145]
I can't seem to find any documentation for how to grab rotation values for the x axis of the pigeon2. For java you bring in the pigeon class from hardware and then put .getRotation2d. It seems that the python implementation has no such function.

I cannot find the .reset or the .getRotation2d
Are they just made different? Or does the python just not have that functionality yet?

This is the Java docs
https://api.ctr-electronics.com/phoenix6/release/java/com/ctre/phoenix6/hardware/Pigeon2.html 

This is the Python docs
https://api.ctr-electronics.com/phoenix6/release/python/autoapi/phoenix6/hardware/core/core_pigeon2/index.html#phoenix6.hardware.core.core_pigeon2.CorePigeon2

**Comment by CoryNessCTR** [comment]
This is an API question already asked in the Phoenix Releases repo, which will be tracked in that repo
https://github.com/CrossTheRoadElec/Phoenix-Releases/issues/69
