### ISSUE TITLE
Lack Of Blocking Call list

### ISSUE THREAD

**Issue by IbrahimAhmad65** [CrossTheRoadElec/Phoenix6-Documentation#148]
The docs do not have a list of blocking calls.

**Comment by bhall-ctre** [comment]
All APIs that are blocking are either documented as such in the API docs (often with the timeout mentioned), or they have a timeout parameter (which may be optional).

Examples:
- [`ParentDevice::optimizeBusUtilizationForAll`](https://api.ctr-electronics.com/phoenix6/latest/java/com/ctre/phoenix6/hardware/ParentDevice.html#optimizeBusUtilizationForAll(com.ctre.phoenix6.hardware.ParentDevice...)) - Documented timeout of 0.100 seconds
- [`BaseStatusSignal::waitForAll`](https://api.ctr-electronics.com/phoenix6/latest/java/com/ctre/phoenix6/BaseStatusSignal.html#waitForAll(double,com.ctre.phoenix6.BaseStatusSignal...)) - Required timeout parameter
- [`BaseStatusSignal::setUpdateFrequency`](https://api.ctr-electronics.com/phoenix6/latest/java/com/ctre/phoenix6/BaseStatusSignal.html#setUpdateFrequency(double)) - Optional timeout parameter, default 0.100 seconds
